// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"net/http"

	v1 "github.com/kuadrant/kcp-glbc/pkg/apis/kuadrant/v1"
	"github.com/kuadrant/kcp-glbc/pkg/client/kuadrant/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type KuadrantV1Interface interface {
	RESTClient() rest.Interface
	DNSRecordsGetter
}

// KuadrantV1Client is used to interact with features provided by the kuadrant.dev group.
type KuadrantV1Client struct {
	restClient rest.Interface
	cluster    string
}

func (c *KuadrantV1Client) DNSRecords(namespace string) DNSRecordInterface {
	return newDNSRecords(c, namespace)
}

// NewForConfig creates a new KuadrantV1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*KuadrantV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new KuadrantV1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*KuadrantV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &KuadrantV1Client{restClient: client}, nil
}

// NewForConfigOrDie creates a new KuadrantV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *KuadrantV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new KuadrantV1Client for the given RESTClient.
func New(c rest.Interface) *KuadrantV1Client {
	return &KuadrantV1Client{restClient: c}
}

// NewWithCluster creates a new KuadrantV1Client for the given RESTClient and cluster.
func NewWithCluster(c rest.Interface, cluster string) *KuadrantV1Client {
	return &KuadrantV1Client{restClient: c, cluster: cluster}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *KuadrantV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
