// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	kuadrantv1 "github.com/kuadrant/kcp-glbc/pkg/apis/kuadrant/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDNSRecords implements DNSRecordInterface
type FakeDNSRecords struct {
	Fake *FakeKuadrantV1
	ns   string
}

var dnsrecordsResource = schema.GroupVersionResource{Group: "kuadrant.dev", Version: "v1", Resource: "dnsrecords"}

var dnsrecordsKind = schema.GroupVersionKind{Group: "kuadrant.dev", Version: "v1", Kind: "DNSRecord"}

// Get takes name of the dNSRecord, and returns the corresponding dNSRecord object, and an error if there is any.
func (c *FakeDNSRecords) Get(ctx context.Context, name string, options v1.GetOptions) (result *kuadrantv1.DNSRecord, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dnsrecordsResource, c.ns, name), &kuadrantv1.DNSRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kuadrantv1.DNSRecord), err
}

// List takes label and field selectors, and returns the list of DNSRecords that match those selectors.
func (c *FakeDNSRecords) List(ctx context.Context, opts v1.ListOptions) (result *kuadrantv1.DNSRecordList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dnsrecordsResource, dnsrecordsKind, c.ns, opts), &kuadrantv1.DNSRecordList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &kuadrantv1.DNSRecordList{ListMeta: obj.(*kuadrantv1.DNSRecordList).ListMeta}
	for _, item := range obj.(*kuadrantv1.DNSRecordList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dNSRecords.
func (c *FakeDNSRecords) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dnsrecordsResource, c.ns, opts))

}

// Create takes the representation of a dNSRecord and creates it.  Returns the server's representation of the dNSRecord, and an error, if there is any.
func (c *FakeDNSRecords) Create(ctx context.Context, dNSRecord *kuadrantv1.DNSRecord, opts v1.CreateOptions) (result *kuadrantv1.DNSRecord, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dnsrecordsResource, c.ns, dNSRecord), &kuadrantv1.DNSRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kuadrantv1.DNSRecord), err
}

// Update takes the representation of a dNSRecord and updates it. Returns the server's representation of the dNSRecord, and an error, if there is any.
func (c *FakeDNSRecords) Update(ctx context.Context, dNSRecord *kuadrantv1.DNSRecord, opts v1.UpdateOptions) (result *kuadrantv1.DNSRecord, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dnsrecordsResource, c.ns, dNSRecord), &kuadrantv1.DNSRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kuadrantv1.DNSRecord), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDNSRecords) UpdateStatus(ctx context.Context, dNSRecord *kuadrantv1.DNSRecord, opts v1.UpdateOptions) (*kuadrantv1.DNSRecord, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(dnsrecordsResource, "status", c.ns, dNSRecord), &kuadrantv1.DNSRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kuadrantv1.DNSRecord), err
}

// Delete takes name of the dNSRecord and deletes it. Returns an error if one occurs.
func (c *FakeDNSRecords) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(dnsrecordsResource, c.ns, name, opts), &kuadrantv1.DNSRecord{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDNSRecords) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dnsrecordsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &kuadrantv1.DNSRecordList{})
	return err
}

// Patch applies the patch and returns the patched dNSRecord.
func (c *FakeDNSRecords) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kuadrantv1.DNSRecord, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dnsrecordsResource, c.ns, name, pt, data, subresources...), &kuadrantv1.DNSRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kuadrantv1.DNSRecord), err
}
