/*
Copyright 2021 The Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/jmprusi/kcp-ingress/pkg/apis/globalloadbalancer/v1alpha1"
	scheme "github.com/jmprusi/kcp-ingress/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GlobalLoadBalancersGetter has a method to return a GlobalLoadBalancerInterface.
// A group's client should implement this interface.
type GlobalLoadBalancersGetter interface {
	GlobalLoadBalancers(namespace string) GlobalLoadBalancerInterface
}

// GlobalLoadBalancerInterface has methods to work with GlobalLoadBalancer resources.
type GlobalLoadBalancerInterface interface {
	Create(ctx context.Context, globalLoadBalancer *v1alpha1.GlobalLoadBalancer, opts v1.CreateOptions) (*v1alpha1.GlobalLoadBalancer, error)
	Update(ctx context.Context, globalLoadBalancer *v1alpha1.GlobalLoadBalancer, opts v1.UpdateOptions) (*v1alpha1.GlobalLoadBalancer, error)
	UpdateStatus(ctx context.Context, globalLoadBalancer *v1alpha1.GlobalLoadBalancer, opts v1.UpdateOptions) (*v1alpha1.GlobalLoadBalancer, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.GlobalLoadBalancer, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.GlobalLoadBalancerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GlobalLoadBalancer, err error)
	GlobalLoadBalancerExpansion
}

// globalLoadBalancers implements GlobalLoadBalancerInterface
type globalLoadBalancers struct {
	client rest.Interface
	ns     string
}

// newGlobalLoadBalancers returns a GlobalLoadBalancers
func newGlobalLoadBalancers(c *NetworkingV1alpha1Client, namespace string) *globalLoadBalancers {
	return &globalLoadBalancers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the globalLoadBalancer, and returns the corresponding globalLoadBalancer object, and an error if there is any.
func (c *globalLoadBalancers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GlobalLoadBalancer, err error) {
	result = &v1alpha1.GlobalLoadBalancer{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("globalloadbalancers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GlobalLoadBalancers that match those selectors.
func (c *globalLoadBalancers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GlobalLoadBalancerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.GlobalLoadBalancerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("globalloadbalancers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested globalLoadBalancers.
func (c *globalLoadBalancers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("globalloadbalancers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a globalLoadBalancer and creates it.  Returns the server's representation of the globalLoadBalancer, and an error, if there is any.
func (c *globalLoadBalancers) Create(ctx context.Context, globalLoadBalancer *v1alpha1.GlobalLoadBalancer, opts v1.CreateOptions) (result *v1alpha1.GlobalLoadBalancer, err error) {
	result = &v1alpha1.GlobalLoadBalancer{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("globalloadbalancers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(globalLoadBalancer).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a globalLoadBalancer and updates it. Returns the server's representation of the globalLoadBalancer, and an error, if there is any.
func (c *globalLoadBalancers) Update(ctx context.Context, globalLoadBalancer *v1alpha1.GlobalLoadBalancer, opts v1.UpdateOptions) (result *v1alpha1.GlobalLoadBalancer, err error) {
	result = &v1alpha1.GlobalLoadBalancer{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("globalloadbalancers").
		Name(globalLoadBalancer.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(globalLoadBalancer).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *globalLoadBalancers) UpdateStatus(ctx context.Context, globalLoadBalancer *v1alpha1.GlobalLoadBalancer, opts v1.UpdateOptions) (result *v1alpha1.GlobalLoadBalancer, err error) {
	result = &v1alpha1.GlobalLoadBalancer{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("globalloadbalancers").
		Name(globalLoadBalancer.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(globalLoadBalancer).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the globalLoadBalancer and deletes it. Returns an error if one occurs.
func (c *globalLoadBalancers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("globalloadbalancers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *globalLoadBalancers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("globalloadbalancers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched globalLoadBalancer.
func (c *globalLoadBalancers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GlobalLoadBalancer, err error) {
	result = &v1alpha1.GlobalLoadBalancer{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("globalloadbalancers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
