// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	kuadrantv1 "github.com/kuadrant/kcp-ingress/pkg/apis/kuadrant/v1"
	versioned "github.com/kuadrant/kcp-ingress/pkg/client/kuadrant/clientset/versioned"
	internalinterfaces "github.com/kuadrant/kcp-ingress/pkg/client/kuadrant/informers/externalversions/internalinterfaces"
	v1 "github.com/kuadrant/kcp-ingress/pkg/client/kuadrant/pkg/client/kuadrant/listers/kuadrant/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DNSRecordInformer provides access to a shared informer and lister for
// DNSRecords.
type DNSRecordInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.DNSRecordLister
}

type dNSRecordInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDNSRecordInformer constructs a new informer for DNSRecord type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDNSRecordInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDNSRecordInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDNSRecordInformer constructs a new informer for DNSRecord type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDNSRecordInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KuadrantV1().DNSRecords(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KuadrantV1().DNSRecords(namespace).Watch(context.TODO(), options)
			},
		},
		&kuadrantv1.DNSRecord{},
		resyncPeriod,
		indexers,
	)
}

func (f *dNSRecordInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDNSRecordInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *dNSRecordInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kuadrantv1.DNSRecord{}, f.defaultInformer)
}

func (f *dNSRecordInformer) Lister() v1.DNSRecordLister {
	return v1.NewDNSRecordLister(f.Informer().GetIndexer())
}
